# Generated by Django 5.0.1 on 2024-01-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyJob',
        ),
    ]
