# Generated by Django 4.2.7 on 2023-12-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=50)),
                ('Paymentmethod', models.CharField(choices=[('c', 'cash on delivery'), ('g', 'gpay')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
